name: Jonathan Glazier
favicon: null
layout_spectrum: 0.15436120121739805
typography_spectrum: 0.6015586049761623
title: Television Production Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5d5d5d'
    - '#afafaf'
    - '#ff0099'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
